[build-system]
requires = ["setuptools >= 77.0.3"]
build-backend = "setuptools.build_meta"

[project]
name = "cvingest"
version = "0.1.0"

dependencies = [
    "pydantic",
    "google-genai",
    "dotenv",
    "PyYaml",
]

requires-python = ">= 3.12"
description = "CV customizer using Gemini into a Latex document"

[tool.setuptools.packages.find]
where = ["src"]

[tool.setuptools.package-data]
cvingest = ["*.txt", "**/*.txt"]